name: SAM CD

on:
  workflow_dispatch:
    inputs:
      stack:
        description: 'Stack name'
        default: 'aialpha-sam'
        required: true
      region:
        description: 'AWS region'
        default: 'eu-north-1'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.region || 'eu-north-1' }}

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Build
        working-directory: oppgave2-sam
        run: sam build

      - name: Deploy
        working-directory: oppgave2-sam
        run: sam deploy --stack-name ${{ inputs.stack }} --resolve-s3 --no-confirm-changeset --no-fail-on-empty-changeset --capabilities CAPABILITY_IAM --region ${{ inputs.region || 'eu-north-1' }}
